image: openjdk:17
stages:
  - tests


teststage:
  stage: tests
  script:
    - chmod +x ./mvnw
    - ./mvnw clean verify

cache:
  paths:
    - .m2/repository
variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
